version: '3.3'
services:
  backend:
    image: screenchecker_backend:latest
    container_name: "screenchecker"
    restart: always
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - ENV_MONGO_HOST=$ENV_MONGO_HOST
      - ENV_MONGO_LOGIN=$ENV_MONGO_LOGIN
      - ENV_MONGO_PASSWORD=$ENV_MONGO_PASSWORD
      - ENV_IMAGE_DIR=$ENV_IMAGE_DIR
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - screenchecker_network
    volumes:
      - screenchecker_backend:/usr/src/app/screenchecker_backend

volumes:
  screenchecker_backend:

networks:
  screenchecker_network: